# 每日任务

name: bilibili-login-task


on:
  workflow_dispatch: # 手动触发

env:
  ASPNETCORE_ENVIRONMENT: ${{secrets.ENV}} # 运行环境

jobs:

  run-login-task:

    runs-on: ubuntu-latest
    environment: Production

    steps:

    # 设置服务器时区为东八区 
    - name: Set time zone
      run: sudo timedatectl set-timezone 'Asia/Shanghai'

    # 检出
    - name: Checkout
      uses: actions/checkout@v2
      
    # .Net 环境
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
 
    # 测试运行
    - name: Test APP
      run: |
        cd ./src/Ray.BiliBiliTool.Console
        dotnet run --runTasks=Login

    - name: Get cookies
      id: cookies
      run: echo "cookies=$(cat /home/runner/work/BiliBiliToolPro/BiliBiliToolPro/src/Ray.BiliBiliTool.Console/cookies.json)" >> $GITHUB_OUTPUT
    - name: Test output
      run: echo ${{ steps.vars.outputs.cookies }}
